import { Inter } from "next/font/google";
import "./globals.css";
import { StateContext } from "./context/Statecontext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Deals Time Store",
  description: "Generated by Hamza Nawaz The Dev",
};

export default function RootLayout({ children }) {
  return (
    <StateContext >
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
    </StateContext>
  );
}
